Update player.yml
voxowl/particubes pull request #78
Opened 2021-05-21 09:30 UTC by FicelleYTB

2021-06-02 10:11 UTC, XLegland requested changes
Thanks for updating the documentation, there some changes to be done, but it is still great work 👍

2021-06-02 10:11 UTC, XLegland commented on lua-docs/content/reference/player.yml
> -      type: "number"
Standard Lua components do not start with a capital letter

2021-06-02 10:11 UTC, XLegland commented on lua-docs/content/reference/player.yml
> +      description: "Set the player animation wave to true or false."
Be more precise about what the property does, like "when set to true, the Player starts waving, it stop when it is set to false". Also do not forget to put brackets around `Player` so it links to the correct page, you could also add ` characters around code words like true.

2021-06-02 10:11 UTC, XLegland commented on lua-docs/content/reference/player.yml
> +     - name: "Wave"
Be careful with the indentation, the hyphen should be at the same column as the one on line 39.

2021-06-02 12:39 UTC, XLegland reviewed
Wave is a function, so it should be placed in the `functions` part

2021-06-04 17:16 UTC, FicelleYTB commented
Ok

2021-07-08 14:03 UTC, aduermael commented
This PR is outdated, closing.

2021-07-08 14:03 UTC, closed without merging